name = "Ainforge"
author = "Trojan-V"
version = "2.0.0"
description = "Ainforge provides pre-configured mods, aiming to provide a seemless experience while playing Cactus Clicker on the PlayLegend server network."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed15f573ffc68324c6b0b914a93ef43a622b3aa74fbfa8e9000be68e13e5a64b"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.8"]
