name = "Ainforge"
author = "Trojan-V"
version = "2.0.0-alpha2"
description = "Ainforge provides pre-configured mods, aiming to provide a seemless experience while playing Cactus Clicker on the PlayLegend server network."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52d72eb70daa66ebf2d82260b17d567f08930581ce71499b3b1c4fed5252ead9"

[versions]
fabric = "0.18.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.8"]
