name: Publish to Modrinth

on:
  push:
    tags:
      - 'v*'  # Trigger bei Version-Tags wie v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Export Modpack
        run: packwiz modrinth export

      - name: Upload to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ImO47DGQ
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: '*.mrpack'
          name: 'Release ${{ github.ref_name }}'
          version: ${{ github.ref_name }}
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: |
            fabric
            forge
          game-versions: |
            1.20.1
            1.20.4
